#!D:\codes and programming\python tutorial\python projects\pyplay mp3 player v3 preinstalled\Python34\python.exe
# -*- coding: utf-8 -*-
# Copyright 2016 Christoph Reiter
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

import sys

from mutagen._tools.mid3cp import entry_point


if __name__ == "__main__":
    sys.exit(entry_point())
